### PR TITLE
Fix Class Name for PretrainedTokenizer

### PR DESCRIPTION
**Pull request by takielias**
### What:

- [ ] Bug Fix

### Description:

The file should be renamed from `PretrainedTokenizer.php` to `PreTrainedTokenizer.php` to adhere to PHP's PSR-1 coding standard and common naming conventions.

### Related:

#70

### CODE REVIEW

**Comment by CodeWithKyrian** [comment]
Thanks for the PR, @takielias. This is a solid contribution. 

That said, I do have one consideration. Since we've decided to standardize on `PreTrainedTokenizer` over `PretrainedTokenizer`, it would make sense to also update the folder name and namespace for consistency throughout the project. 

However, my concern is the potential for this to introduce a breaking change for users on systems with case-sensitive namespaces. It may lead to holding off on tagging this as a release until version 0.6.0, to give us time to manage this transition smoothly.

Could you go ahead and update the namespace and folder first? We can then discuss the best way to proceed from there. 

Thanks again for your work!

**Comment by takielias** [comment]
@CodeWithKyrian sure, I will share the update.

**Comment by takielias** [comment]
@CodeWithKyrian Hi, I have updated the Folder name as well as the Namespace.

**Comment by CodeWithKyrian** [comment]
Perfect. Thanks so much for your contribution

**Pull request merged**
